apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-deployment
spec:
  selector:
    matchLabels:
      app: star-wars
  replicas: 2
  template:
    metadata:
      labels:
        app: star-wars
    spec:
      containers:
        - name: starwars-node
          image: steingrim/starwars-node:0.0.3
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "150Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "250m"
