# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        cd python_flask
        docker build -t python-flask .

    - name: Build another image
      run: |
        cd express_server
        docker build -t starwars-node .

    - name: List images
      run: docker images

    - name: Deploy to node app
      run: |
        kubectl apply -f sw-deployment.yml
    
    - name: Deploy to flask app
      run: kubectl apply -f py-deployment.yml

    - name: Test service URLs
      run: |
        minikube service list
        minikube service example --url
        echo "------------------opening the service------------------"
        curl $(minikube service example --url)  