name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
     - name: Test
       run: |
        pwd
        cd ..
        ls
        pwd
     -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./python_flask
          push: true
          tags: user/app:latest
  job1:
    runs-on: ubuntu-latest
    name: deploy services to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        cd python_flask
        docker build -t python-flask .

    - name: Build another image
      run: |
        cd express_server
        docker build -t starwars-node .

    - name: List images
      run: docker images

    - name: Deploy to node app
      run: |
        kubectl apply -f sw-deployment.yml
    
    - name: Deploy to flask app
      run: kubectl apply -f py-deployment.yml

    - name: Create node service
      run: kubectl apply -f sw-service.yml

    - name: Create python service
      run: kubectl apply -f py-service.yml

    - name: Test service URLs
      run: |
        minikube service sw-service --url
        curl $(minikube service sw-service --url)
        minikube service py-service --url
        curl $(minikube service py-service --url)